(() => {
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const W=2400,H=1200, player={x:265,y:595,r:17,speed:270}, keys={}, touch={};
  const biomes=[
    {id:'forest',name:'Forest Frontier',range:[0,620],base:'#3f8b59',dark:'#206642',accent:'#8fc968'},
    {id:'desert',name:'Sunkissed Dunes',range:[620,1200],base:'#dca95b',dark:'#bb7042',accent:'#f5d36a'},
    {id:'mountain',name:'Frostpeak Range',range:[1200,1810],base:'#829bb1',dark:'#536c88',accent:'#e6f4f5'},
    {id:'caves',name:'Glimmerdeep Caves',range:[1810,2400],base:'#4a4265',dark:'#2a2847',accent:'#bd7ae7'}
  ];
  const squares=[
    ['forest','Canopy Cube',165,235,'Look beneath the tall pines.','#8eff72'],['forest','Mossy Marker',410,795,'A quiet stone arch guards it.','#74e6a0'],['forest','Cascade Square',555,350,'Listen for falling water.','#64dfff'],['forest','Hollow Tile',275,1035,'A fallen giant keeps this secret.','#e8c76d'],['forest','Ruin Ruby',535,965,'Old walls hide a bright treasure.','#ff8062'],
    ['desert','Oasis Opal',760,295,'Palms shade this cool discovery.','#64dcce'],['desert','Dune Diamond',910,760,'The winds have tucked it away.','#ffe271'],['desert','Canyon Cube',1115,365,'Look between the red stone walls.','#f8755e'],['desert','Obelisk Square',1010,1000,'An ancient spire points the way.','#b485ff'],['desert','Sunken Tile',695,980,'Search where the sand swallowed a temple.','#ffb14f'],
    ['mountain','Cliffside Cube',1325,310,'A narrow ledge offers a wide view.','#dceffc'],['mountain','Bridge Block',1515,720,'Cross the old rope bridge.','#f3c164'],['mountain','Summit Square',1745,250,'The highest flag knows its home.','#ff6e77'],['mountain','Campfire Tile',1430,1030,'A cold camp waits in the snow.','#ffb84d'],['mountain','Snowcap Gem',1770,950,'The white peak has a colorful secret.','#7be9ff'],
    ['caves','Crystal Cube',1940,350,'Purple crystals light the path.','#e994ff'],['caves','Echo Square',2170,720,'Listen for the hidden waterfall.','#7ddcff'],['caves','Ember Block',2030,1010,'Walk where the lava rocks glow.','#ff735c'],['caves','Miner Tile',2340,290,'A forgotten tunnel ends with a prize.','#f4d662'],['caves','Heartstone Square',2290,950,'The deepest chamber keeps its heart.','#ff78b5']
  ].map((s,i)=>({id:`sq-${i}`,biome:s[0],name:s[1],x:s[2],y:s[3],hint:s[4],color:s[5]}));
  let found=JSON.parse(localStorage.getItem('find-the-squares-found')||'{}'), tab='all', camera={x:0,y:0}, last=0, toastTimer;
  const $=s=>document.querySelector(s), grid=$('#catalogGrid'), backdrop=$('#backdrop'), confirm=$('#confirmBackdrop');
  function save(){localStorage.setItem('find-the-squares-found',JSON.stringify(found))} function count(){return Object.keys(found).length}
  function updateUI(){let n=count();$('#progressText').textContent=`${n} / 20`;$('#meterFill').style.width=`${n/20*100}%`;$('#catalogSummary').textContent=`${n} of 20 squares discovered`;renderCatalog()}
  function showToast(s){const t=$('#toast');t.innerHTML=`<span style="color:${s.color}">◆</span> ${s.name} found!`;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
  function currentBiome(){return biomes.find(b=>player.x>=b.range[0]&&player.x<b.range[1])||biomes[3]}
  function renderCatalog(){const groups=tab==='all'?biomes:biomes.filter(b=>b.id===tab);grid.innerHTML=groups.flatMap(b=>squares.filter(s=>s.biome===b.id).map(s=>{let f=found[s.id];return `<article class="square-card ${f?'':'missing'}"><div class="square-icon" style="background:${s.color}"></div><div><h3>${f?s.name:'Unknown Square'}</h3><p>${f?b.name:s.hint}</p>${f?`<span class="found-date">FOUND ${f}</span>`:''}</div></article>`})).join('');$('#catalogTabs').innerHTML=[['all','All squares'],...biomes.map(b=>[b.id,b.name])].map(([id,label])=>`<button class="${tab===id?'active':''}" role="tab" aria-selected="${tab===id}" data-tab="${id}">${label}</button>`).join('');$('#catalogTabs').querySelectorAll('button').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;renderCatalog()})}
  function openCatalog(){backdrop.hidden=false;renderCatalog();$('#closeCatalog').focus()} function closeCatalog(){backdrop.hidden=true;$('#catalogButton').focus()}
  $('#catalogButton').onclick=openCatalog;$('#closeCatalog').onclick=closeCatalog;backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeCatalog()});
  $('#resetButton').onclick=()=>{confirm.hidden=false;$('#cancelReset').focus()};$('#cancelReset').onclick=()=>confirm.hidden=true;$('#confirmReset').onclick=()=>{found={};save();updateUI();confirm.hidden=true;closeCatalog();showToast({name:'Fresh adventure started',color:'#ffd34f'})};
  window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.key==='Escape'){if(!confirm.hidden)confirm.hidden=true;else if(!backdrop.hidden)closeCatalog()}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
  document.querySelectorAll('[data-direction]').forEach(b=>{let d=b.dataset.direction;['pointerdown','pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();touch[d]=ev==='pointerdown'}))});
  function resize(){let r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}window.addEventListener('resize',resize);resize();
  function drawTree(x,y,c){ctx.fillStyle='#275a3c';ctx.fillRect(x-5,y,10,24);ctx.fillStyle=c;[[0,-27,18],[13,-13,14],[-13,-12,15],[0,-40,13]].forEach(([a,b,r])=>{ctx.beginPath();ctx.arc(x+a,y+b,r,0,7);ctx.fill()})}
  function worldX(x){return x-camera.x} function worldY(y){return y-camera.y}
  function drawScene(vw,vh){ctx.clearRect(0,0,vw,vh);biomes.forEach((b,i)=>{ctx.fillStyle=b.base;ctx.fillRect(worldX(b.range[0]),worldY(0),b.range[1]-b.range[0],H);ctx.fillStyle=b.dark+'30';for(let n=0;n<13;n++){let x=b.range[0]+((n*79+67)%Math.max(1,b.range[1]-b.range[0])),y=80+((n*157)%1060);ctx.beginPath();ctx.arc(worldX(x),worldY(y),20+(n%3)*8,0,7);ctx.fill()}});
    // biome markers / terrain decorations
    for(let x=70;x<600;x+=88)for(let y=95;y<H;y+=120)drawTree(worldX(x),worldY(y),'#4f9b57');
    ctx.fillStyle='#60b9d1';ctx.fillRect(worldX(548),worldY(110),18,370);ctx.fillStyle='#2e7faa';ctx.fillRect(worldX(555),worldY(110),7,370);
    ctx.fillStyle='#5b94af';[[1300,610],[1460,375],[1640,820],[1780,480]].forEach(([x,y])=>{ctx.beginPath();ctx.moveTo(worldX(x-95),worldY(y+90));ctx.lineTo(worldX(x),worldY(y-105));ctx.lineTo(worldX(x+110),worldY(y+90));ctx.closePath();ctx.fill();ctx.fillStyle='#edf7fb';ctx.beginPath();ctx.moveTo(worldX(x-34),worldY(y-40));ctx.lineTo(worldX(x),worldY(y-105));ctx.lineTo(worldX(x+43),worldY(y-30));ctx.closePath();ctx.fill();ctx.fillStyle='#5b94af'});
    ctx.strokeStyle='#6b4936';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(worldX(1460),worldY(715));ctx.lineTo(worldX(1580),worldY(750));ctx.stroke();
    for(let x=1880;x<2390;x+=100){ctx.fillStyle='#7157a0';ctx.beginPath();ctx.moveTo(worldX(x),worldY(260+(x%4)*120));ctx.lineTo(worldX(x+14),worldY(220+(x%4)*120));ctx.lineTo(worldX(x+28),worldY(260+(x%4)*120));ctx.closePath();ctx.fill()}
    // region name labels
    biomes.forEach(b=>{let cx=(b.range[0]+b.range[1])/2;ctx.fillStyle='#fff8';ctx.font='900 14px Nunito';ctx.textAlign='center';ctx.fillText(b.name.toUpperCase(),worldX(cx),worldY(72))});
    squares.forEach(s=>{let x=worldX(s.x),y=worldY(s.y),f=found[s.id];if(f)return;ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillStyle='#182735';ctx.fillRect(-13,-11,27,27);ctx.fillStyle=s.color;ctx.fillRect(-11,-13,23,23);ctx.fillStyle='#fff8';ctx.fillRect(-8,-10,9,9);ctx.restore();ctx.fillStyle='#fff';ctx.font='900 12px Nunito';ctx.textAlign='center';ctx.fillText('?',x,y-24)});
    // player
    let px=worldX(player.x),py=worldY(player.y);ctx.fillStyle='#15243177';ctx.beginPath();ctx.ellipse(px,py+17,18,7,0,0,7);ctx.fill();ctx.fillStyle='#ffca50';ctx.beginPath();ctx.arc(px,py-8,13,0,7);ctx.fill();ctx.fillStyle='#243c56';ctx.fillRect(px-13,py+3,26,21);ctx.fillStyle='#80dbdc';ctx.fillRect(px-10,py+7,20,9);ctx.fillStyle='#fff';ctx.fillRect(px-7,py-10,3,3);ctx.fillRect(px+4,py-10,3,3)
  }
  function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;if(backdrop.hidden&&confirm.hidden){let dx=(keys.d||keys.arrowright||touch.right?1:0)-(keys.a||keys.arrowleft||touch.left?1:0),dy=(keys.s||keys.arrowdown||touch.down?1:0)-(keys.w||keys.arrowup||touch.up?1:0);if(dx||dy){let m=Math.hypot(dx,dy);player.x=Math.max(25,Math.min(W-25,player.x+dx/m*player.speed*dt));player.y=Math.max(25,Math.min(H-25,player.y+dy/m*player.speed*dt))}squares.forEach(s=>{if(!found[s.id]&&Math.hypot(player.x-s.x,player.y-s.y)<38){found[s.id]=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});save();updateUI();showToast(s)}})}let rect=canvas.getBoundingClientRect();camera.x=Math.max(0,Math.min(W-rect.width,player.x-rect.width/2));camera.y=Math.max(0,Math.min(H-rect.height,player.y-rect.height/2));drawScene(rect.width,rect.height);let b=currentBiome();$('#biomePill').textContent=b.name;$('#biomePill').style.background=b.dark+'e6';requestAnimationFrame(loop)}updateUI();requestAnimationFrame(loop);
})();
